### ISSUE TITLE
CSI drivers should not depend on Kubernetes

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/drivers#9]
It's fairly common to see importing Kubernetes in our drivers:

```
Import (
	"k8s.io/kubernetes/pkg/util/mount"
	"k8s.io/kubernetes/pkg/volume/util"
)
```

The drivers should be totally independent on Kubernetes and should not import it.

**Comment by chakri-nelluri** [comment]
Plan is to move some of the utilities to https://github.com/kubernetes/utils and load it from there.
I referred to other external controllers like ingress and they are currently importing from the tree. I agree with you. It is not great, but for now rather than duplicating all this code, which in-turn is referring to other K8S packages, I add this dependency.

**Comment by humblec** [comment]
Otherwise we need to pull these `utils` to `csi-common` in this repo.
